### ISSUE TITLE
Regularly adds and/or removes {}

### ISSUE THREAD

**Issue by iggyvolz** [shapedbyregret/actionscript-3-obfuscator#1]
This program works perfectly, except for the fact that it adds or removes { or }, breaking the syntax and requiring manual labor to fix.

**Comment by shapedbyregret** [comment]
Do you have an example file I can test with?

**Comment by iggyvolz** [comment]
hmm... I made a simpler file and it worked perfectly, of course as soon as I try to show someone it works perfectly fine!

I'm going to try to figure out why it broke in my original file.

**Comment by iggyvolz** [comment]
huh... now it works perfectly fine on the original file that it was supposed to obfuscate...

I must have called it wrong the first time I did it... I'll close this for now.

**Comment by iggyvolz** [comment]
This seems to be related to the way I'm trying to do it recursively to all files in directory:

for file in *.as; do python ~/obfuscator.py $file;done

Oh well, I'll just generate a script to put in the filenames manually.

**Comment by iggyvolz** [comment]
Guess not, it still makes the same mistake individually.
@shapedbyregret could I send you my file through email? It's for a game I'm doing and I don't want to make the ActionScript public

**Comment by shapedbyregret** [comment]
Yes, that's fine. That will help a lot in narrowing down the problem.

**Comment by iggyvolz** [comment]
I sent it.  It refers to a few other classes, if you want to know what those do, just send me an email.  I also removed out my password from the script.

**Comment by iggyvolz** [comment]
Worked like a charm!  Thank you very much!
